version: "3.9"

services:
  api_chronos:
    container_name: api_chronos
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=PRODUCTION
    env_file:
      - .env.prod
    depends_on:
      - db_chronos
    networks:
      - chronos_network
    command: sh -c "npx prisma migrate deploy && npm start"

  db_chronos:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chronos_network
      
volumes:
  postgres_data:

networks:
  chronos_network:
    driver: bridge