services:
  api_chronos:
    container_name: api_chronos
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db_chronos
    command: >
      sh -c "npx prisma migrate deploy && npm start"
    networks:
      - chronos_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db_chronos
    networks:
      - chronos_network

  db_chronos:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chronos_network

volumes:
  postgres_data:
    driver: local

networks:
  chronos_network:
    driver: bridge
