global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-app'
    scheme: https
    scrape_interval: 5s
    static_configs:
      - targets: ['chronos-latest.onrender.com']