name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      # 4️⃣ Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chronos:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chronos:latest

      # 6️⃣ Rodar containers com docker-compose
      - name: Build e Deploy com docker-compose
        run: |
          docker-compose up -d --build
