# Nome da esteira de CD
name: Continuous Delivery
 
# Dispara o CD sempre que der push na branch main
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chronos:latest .

      - name: Push da imagem
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chronos:latest